# Generated by Django 4.2.7 on 2023-11-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_movie_genres'),
        ('accounts', '0003_remove_user_like_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(related_name='genre_like_users', to='movies.genre'),
        ),
    ]
