# Generated by Django 4.2.7 on 2023-11-20 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('movies', models.ManyToManyField(to='movies.movie')),
                ('regions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movie')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.reservation')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.seat')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.theater')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.playdate')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.theater'),
        ),
        migrations.AddField(
            model_name='seat',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.playdate'),
        ),
        migrations.AddField(
            model_name='playdate',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.theater'),
        ),
    ]
