# Generated by Django 4.2.7 on 2023-11-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playdate',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='playdate',
            name='time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='col',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=5),
        ),
    ]
