# Generated by Django 4.2.7 on 2023-11-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_alter_playdate_date_alter_playdate_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='theater',
        ),
    ]
